### ISSUE TITLE
页面停留时长，是否得自己主动上报？

### ISSUE THREAD

**Issue by tomatobybike** [chengpeiquan/vue-cnzz-analytics#4]
页面停留时长，是否得自己主动上报？

**Comment by tomatobybike** [comment]
目前看，统计不到页面停留时长

**Comment by chengpeiquan** [comment]
停留时长这块目前没有手动上报的办法…

**Comment by tomatobybike** [comment]
router.afterEach(function (to, form) {
          var PAGE_PATH_DIR_COUNT = window.location.pathname.split('/').length;
          var PAGE_PATH = window.location.pathname.split('/').slice(0, PAGE_PATH_DIR_COUNT - 1).join('/');
          var PAGE_URL = router.mode === 'hash' ? PAGE_PATH + "/#" + to.fullPath : "" + PAGE_PATH + to.fullPath;
          var FROM = router.mode === 'hash' ? PAGE_PATH + "/#" + from.fullPath : "" + PAGE_PATH + from.fullPath;
          pushCNZZ.pv(PAGE_URL, FROM);
      });

=======================
这样就可以统计到停留时长了
